# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ConnectDBMenu(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_menu_title = QtWidgets.QLabel(Form)
        self.lbl_menu_title.setObjectName("label")
        self.verticalLayout.addWidget(self.lbl_menu_title)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_choice_db_type = QtWidgets.QLabel(Form)
        self.lbl_choice_db_type.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.lbl_choice_db_type)
        self.box_db_types = QtWidgets.QComboBox(Form)
        self.box_db_types.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.box_db_types)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_host = QtWidgets.QLabel(Form)
        self.lbl_host.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.lbl_host)
        self.le_host = QtWidgets.QLineEdit(Form)
        self.le_host.setEnabled(True)
        self.le_host.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.le_host)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_port = QtWidgets.QLabel(Form)
        self.lbl_port.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.lbl_port)
        self.le_port = QtWidgets.QLineEdit(Form)
        self.le_port.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.le_port)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_user = QtWidgets.QLabel(Form)
        self.lbl_user.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.lbl_user)
        self.le_user = QtWidgets.QLineEdit(Form)
        self.le_user.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.le_user)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_pass = QtWidgets.QLabel(Form)
        self.lbl_pass.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.lbl_pass)
        self.le_pass = QtWidgets.QLineEdit(Form)
        self.le_pass.setObjectName("lineEdit_6")
        self.le_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.horizontalLayout_6.addWidget(self.le_pass)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_db_name = QtWidgets.QLabel(Form)
        self.lbl_db_name.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.lbl_db_name)
        self.le_db_name = QtWidgets.QLineEdit(Form)
        self.le_db_name.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.le_db_name)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.btn_connect_db = QtWidgets.QPushButton(Form)
        self.btn_connect_db.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.btn_connect_db)
        self.horizontalLayout_7.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_menu_title.setText(_translate("Form", "Меню подключения Базы Данных"))
        self.lbl_choice_db_type.setText(_translate("Form", "Выберите СУБД"))
        self.lbl_host.setText(_translate("Form", "Host"))
        self.lbl_port.setText(_translate("Form", "Port"))
        self.lbl_user.setText(_translate("Form", "User"))
        self.lbl_pass.setText(_translate("Form", "Password"))
        self.lbl_db_name.setText(_translate("Form", "DataBase"))
        self.btn_connect_db.setText(_translate("Form", "Подключить"))
